template:
    applicationname: edna
    jobname: cdc-sampled-streamer-local
    filename: CDCSampledStreamer
    jobcontext: ednaconf
    jobreplicas: 1
    jobtype: internal
    jobimage: 
      registryaddress: localhost:5000
      imagetag: latest
    jobgraph:
      import_key: "in-topic"
      export_key: "out-topic"
    jobvariables:
      import_topic: "in-topic"
      import_key: "out-topic"